export default [
  {type: 'text', authorType: "me", data: { text: "Why don't they have salsa on the table?"} },
  {type: 'text', authorType: "them", data: { text: "What do you need salsa for?"} },
  {type: 'text', authorType: "me", data: { text: "Salsa is now the number one condiment in America."} },
  {type: 'text', authorType: "them", data: { text: "You know why? Because people like to say 'salsa.' 'Excuse me, do you have salsa?' 'We need more salsa.' 'Where is the salsa? No salsa?'"} },
  {type: 'text', authorType: "me", data: { text: "You know it must be impossible for a Spanish person to order seltzer and not get salsa. 'I wanted seltzer, not salsa.'"} },
  {type: 'text', authorType: "them", data: { text: "Don't you know the difference between seltzer and salsa?? You have the seltezer after the salsa!"} },
  {type: 'text', authorType: "me", data: { text: "See, this should be a show. This is the show. "} },
  {type: 'text', authorType: "them", data: { text: "What?"} },
  {type: 'text', authorType: "me", data: { text: "This. Just talking."} },
  {type: 'text', authorType: "them", data: { text: "Yeah, right."} },
  {type: 'text', authorType: "me", data: { text: "I'm really serious. I think that's a good idea. "} },
  {type: 'text', authorType: "them", data: { text: "Just talking? Well what's the show about?"} },
  {type: 'text', authorType: "me", data: { text: "It's about nothing."} },
  {type: 'text', authorType: "them", data: { text: "No story?"} },
  {type: 'text', authorType: "me", data: { text: "No forget the story. "} },
  {type: 'text', authorType: "them", data: { text: "You've got to have a story."} },
  {type: 'emoji', authorType: "me", data: { emoji: "😋"} },
]